In [2]:
import pandas as pd
from scipy import stats as st
import re
import glob
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt

# Задание 1

In [60]:
df = pd.read_csv('/Users/alex/Лекции/Статистика/video_games_sales.csv')
df = df.astype(object).replace(np.nan, 'None')

In [92]:
df

,Rank,Name,basename,Genre,ESRB_Rating,Platform,Publisher,Developer,VGChartz_Score,Critic_Score,...,NA_Sales,PAL_Sales,JP_Sales,Other_Sales,Year,Last_Update,url,status,Vgchartzscore,img_url
0,1,Wii Sports,wii-sports,Sports,E,Wii,Nintendo,Nintendo EAD,None,7.7,...,None,None,None,None,2006,None,http://www.vgchartz.com/game/2667/wii-sports/?...,1,None,/games/boxart/full_2258645AmericaFrontccc.jpg
1,2,Super Mario Bros.,super-mario-bros,Platform,None,NES,Nintendo,Nintendo EAD,None,10,...,None,None,None,None,1985,None,http://www.vgchartz.com/game/6455/super-mario-...,1,None,/games/boxart/8972270ccc.jpg
2,3,Mario Kart Wii,mario-kart-wii,Racing,E,Wii,Nintendo,Nintendo EAD,None,8.2,...,None,None,None,None,2008,11th Apr 18,http://www.vgchartz.com/game/6968/mario-kart-w...,1,8.7,/games/boxart/full_8932480AmericaFrontccc.jpg
3,4,PlayerUnknown's Battlegrounds,playerunknowns-battlegrounds,Shooter,None,PC,PUBG Corporation,PUBG Corporation,None,None,...,None,None,None,None,2017,13th Nov 18,http://www.vgchartz.com/game/215988/playerunkn...,1,None,/games/boxart/full_8052843AmericaFrontccc.jpg
4,5,Wii Sports Resort,wii-sports-resort,Sports,E,Wii,Nintendo,Nintendo EAD,None,8,...,None,None,None,None,2009,None,http://www.vgchartz.com/game/24656/wii-sports-...,1,8.8,/games/boxart/full_7295041AmericaFrontccc.jpg
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55787,55788,Indivisible,indivisible,Role-Playing,None,PC,505 Games,Lab Zero Games,None,None,...,None,None,None,None,2019,11th Apr 19,http://www.vgchartz.com/game/224682/indivisibl...,1,None,/games/boxart/full_6339426AmericaFrontccc.jpg
55788,55789,Lost Ember,lost-amber,Adventure,RP,PC,Mooneye Studios,Mooneye Studios,None,None,...,None,None,None,None,2019,11th Apr 19,http://www.vgchartz.com/games/game.php?id=2246...,1,None,/games/boxart/full_8893129AmericaFrontccc.jpg
55789,55790,Lost Ember,lost-amber,Adventure,RP,PS4,Mooneye Studios,Mooneye Studios,None,None,...,None,None,None,None,2019,11th Apr 19,http://www.vgchartz.com/game/224690/lost-ember...,1,None,/games/boxart/full_6514293AmericaFrontccc.jpg
55790,55791,Lost Ember,lost-amber,Adventure,RP,XOne,Mooneye Studios,Mooneye Studios,None,None,...,None,None,None,None,2019,11th Apr 19,http://www.vgchartz.com/game/224688/lost-ember...,1,None,/games/boxart/full_6799693AmericaFrontccc.jpg
55791,55792,Falcon Age,falcon-age,Action-Adventure,None,PS4,Unknown,Outerloop Games,None,None,...,None,None,None,None,None,12th Apr 19,http://www.vgchartz.com/game/224692/falcon-age...,1,None,/games/boxart/default.jpg

In [61]:
Sports = df[(df['Genre'] == 'Sports') & (df['Critic_Score'] != 'None')]

In [62]:
Other_Genre = df[(df['Genre'] != 'Sports') & (df['Critic_Score'] != 'None')]

In [68]:
alpha = 0.05
result = st.ttest_ind(Sports['Critic_Score'], Other_Genre['Critic_Score'], equal_var=False)
print(result)
print(Sports['Critic_Score'].mean())
print(Other_Genre['Critic_Score'].mean())

if (result.pvalue < alpha):
    print('Отвергаем нулевую гипотезу, критики по другому относяться к спортивным играм')
else:
    print('Не отвергаем нулевую гипотезу, критики относяться к жанру Sport, так же как и к остальным жанрам')

Ttest_indResult(statistic=1.46718225528123, pvalue=0.14269539749721827)
7.291424418604655
7.2045656634747255
Не отвергаем нулевую гипотезу, критики относяться к жанру Sport, так же как и к остальным жанрам

In [80]:
PC = df[(df['Platform'] == 'PC') & (df['Critic_Score'] != 'None')]

In [81]:
PS4 = df[(df['Platform'] == 'PS4') & (df['Critic_Score'] != 'None')]

In [93]:
alpha = 0.05
result = st.ttest_ind(PC['Critic_Score'], PS4['Critic_Score'], equal_var=False)
print(result)
print('Средний рейтин PC', PC['Critic_Score'].mean())
print('Средний рейтин PS4', PS4['Critic_Score'].mean())

if (result.pvalue < alpha):
    print('Отвергаем нулевую гипотезу, критики по разному относяться к играм на PC и на PS4')
    if PC['Critic_Score'].mean() > PS4['Critic_Score'].mean():
        print ('Критики больше любят игры на PC')
    else:
        print ('Критики больше любят игры на PS4')
else:
    print('Не отвергаем нулевую гипотезу, критики относяться к жанру Sport, так же как и к остальным жанрам')

Ttest_indResult(statistic=-2.739447605635148, pvalue=0.0069318082502545075)
Средний рейтин PC 7.541849710982658
Средний рейтин PS4 7.904587155963299
Отвергаем нулевую гипотезу, критики по разному относяться к играм на PC и на PS4
Критики больше любят игры на PS4

In [89]:
Shooter = df[(df['Genre'] == 'Shooter') & (df['Critic_Score'] != 'None')]

In [90]:
Strategy = df[(df['Genre'] == 'Strategy') & (df['Critic_Score'] != 'None')]

In [91]:
alpha = 0.05
result = st.ttest_ind(Strategy['Critic_Score'], Shooter['Critic_Score'], equal_var=False)
print(result)
print('Средний рейтин жанра - Strategy', Strategy['Critic_Score'].mean())
print('Средний рейтин жанры - Shooter', Shooter['Critic_Score'].mean())

if (result.pvalue < alpha):
    print('Отвергаем нулевую гипотезу, критики по разному относяться к жанрам')
    if Strategy['Critic_Score'].mean() > Shooter['Critic_Score'].mean():
        print ('Критики больше Стратегии')
    else:
        print ('Критики больше Шутеры')
else:
    print('Не отвергаем нулевую гипотезу, критики относяться к жанрам одинаково')

Ttest_indResult(statistic=1.6073949711166018, pvalue=0.10838786414224187)
Средний рейтин жанра - Strategy 7.429268292682925
Средний рейтин жанры - Shooter 7.2868327402135264
Не отвергаем нулевую гипотезу, критики относяться к жанрам одинаково

# Задание 2

In [110]:
df = pd.read_csv('https://raw.githubusercontent.com/obulygin/pyda_homeworks/master/stat_case_study/spam.csv')

In [111]:
df['Message'] = df['Message'].str.lower()

In [112]:
df['Message'] = df['Message'].str.replace(r'[\W_]+', ' ')

In [113]:
from nltk.corpus import stopwords

In [114]:
stop = stopwords.words('english')
df['Message'] = df['Message'].apply(lambda x: ' '.join([word for word in x.split() if word not in (stop)]))

In [115]:
from nltk.stem import WordNetLemmatizer

In [116]:
wordnet_lemmatizer = WordNetLemmatizer()
df['Message'] = [' '.join([wordnet_lemmatizer.lemmatize(word) for word in x.split()]) for x in df['Message'].tolist()]

In [117]:
df

     Category                                            Message
0         ham  go jurong point crazy available bugis n great ...
1         ham                            ok lar joking wif u oni
2        spam  free entry 2 wkly comp win fa cup final tkts 2...
3         ham                u dun say early hor u c already say
4         ham                nah think go usf life around though
...       ...                                                ...
5567     spam  2nd time tried 2 contact u u 750 pound prize 2...
5568      ham                        ü b going esplanade fr home
5569      ham                               pity mood suggestion
5570      ham  guy bitching acted like interested buying some...
5571      ham                                     rofl true name

[5572 rows x 2 columns]

In [118]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [119]:
tfidf = TfidfVectorizer()
tfidf_matrix = tfidf.fit_transform(df.Message)
names = tfidf.get_feature_names()
tfidf_matrix = pd.DataFrame(tfidf_matrix.toarray(), columns=names)
tfidf_matrix

,00,000,000pes,008704050406,0089,0121,01223585236,01223585334,0125698789,02,...,zhong,zindgi,zoe,zogtorius,zoom,zouk,zyada,èn,ú1,〨ud
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5567,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5568,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5569,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5570,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5571,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [120]:
def my_funcion(column): 
    if column['Category'] == 'ham' :
        return 0
    if column['Category'] == 'spam' :
        return 1

df['Tag'] = df.apply(my_funcion, axis=1)

In [121]:
x = tfidf_matrix

In [122]:
y = df['Tag'].tolist()

In [123]:
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_iris
from sklearn.linear_model import LogisticRegression

In [124]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.30, random_state=42)

In [125]:
clf = LogisticRegression(random_state=42).fit(x_train, y_train)

In [126]:
result = pd.DataFrame([y_test, clf.predict(x_test)]).T

In [127]:
result.head(5)

   0  1
0  0  0
1  0  0
2  0  0
3  0  0
4  0  0

In [128]:
from sklearn.metrics import confusion_matrix

In [129]:
confusion_matrix(y_test, clf.predict(x_test))

array([[1445,    3],
       [  66,  158]])

In [130]:
pred = LogisticRegression(random_state=42).fit(x, y)

In [131]:
df['pred'] = clf.predict(x)

In [132]:
df

     Category                                            Message  Tag  pred
0         ham  go jurong point crazy available bugis n great ...    0     0
1         ham                            ok lar joking wif u oni    0     0
2        spam  free entry 2 wkly comp win fa cup final tkts 2...    1     1
3         ham                u dun say early hor u c already say    0     0
4         ham                nah think go usf life around though    0     0
...       ...                                                ...  ...   ...
5567     spam  2nd time tried 2 contact u u 750 pound prize 2...    1     1
5568      ham                        ü b going esplanade fr home    0     0
5569      ham                               pity mood suggestion    0     0
5570      ham  guy bitching acted like interested buying some...    0     0
5571      ham                                     rofl true name    0     0

[5572 rows x 4 columns]